### ISSUE TITLE
Android exception

### ISSUE THREAD

**Issue by bjgross1076** [MikeMaxwell/vmgr#1]
Getting and exception trying to add a zone
LogsClear
6ace45df-b382-46ef-afad-d51409241322  11:35:27 AM: error java.lang.NumberFormatException @ line 418
6ace45df-b382-46ef-afad-d51409241322  11:35:27 AM: debug Updated with settings: [tempSensors:Master Multi Sensor, staticHSP:70, staticCSP:70, zoneControlType:offset, minVo:0, heatOffset:0, coolOffset:0, vents:[Master Smart Vent], maxVo:100]
6ace45df-b382-46ef-afad-d51409241322  11:35:26 AM: debug Installed with settings: [tempSensors:Master Multi Sensor, staticHSP:70, staticCSP:70, zoneControlType:offset, minVo:0, heatOffset:0, coolOffset:0, vents:[Master Smart Vent], maxVo:100]

**Comment by MikeMaxwell** [comment]
should be fixed  Keenect 1.0.0a 2015-02-14 Fix zone init NPE error on heat only
you only need to update Keenect., please verify this resolves the issue

**Comment by bjgross1076** [comment]
Unfort. still erroring.  

Error when trying to add keenect:

2563a3c4-1208-4e1b-8747-5242904eb1b0  ‎12‎:‎32‎:‎43‎ ‎PM: error java.lang.NumberFormatException @ line 65 

2563a3c4-1208-4e1b-8747-5242904eb1b0  ‎12‎:‎32‎:‎43‎ ‎PM: debug Updated with settings: [tempSensors:Nest Thermostat, tStat:Nest Thermostat, isACcapable:true] 

If I back out of setup, it adds the app. Then trying to add a zone, I get:

598b3ba8-3f57-4cf6-98e8-a82f5703deb0  ‎12‎:‎35‎:‎18‎ ‎PM: error java.lang.NumberFormatException @ line 424 

598b3ba8-3f57-4cf6-98e8-a82f5703deb0  ‎12‎:‎35‎:‎18‎ ‎PM: debug Updated with settings: [coolOffset:0, staticCSP:73, vents:[Alex Smart Vent], tempSensors:Alex Motion Sensor, staticHSP:70, zoneControlType:fixed, minVo:0, heatOffset:0, maxVo:100]
