### ISSUE TITLE
Unable Setup

### ISSUE THREAD

**Issue by caesra** [MikeMaxwell/vmgr#2]
When executing setup of the main application (from Web) I am able to install, and it shows the two devices after installation.  But I am unable to retrieve any information if I browse back to the device.  If I install the main application from the marketplace I receive the errors below. I am unable to setup any vents or go back in to the app and see the installation.  The install does show in the my locations > smart apps.  I can do multiple installs.

4726a854-b87b-499b-a8e1-277a51f19442  8:53:05 PM: debug parseReportAttributeMessage
4726a854-b87b-499b-a8e1-277a51f19442  8:53:05 PM: debug description: read attr - raw: D7400104030C200022A3F80E, dni: D740, endpoint: 01, cluster: 0403, size: 0C, attrId: 0020, encoding: 22, value: 0ef8a3
4726a854-b87b-499b-a8e1-277a51f19442  8:53:05 PM: debug Parse returned [name:temperature, value:68.22, descriptionText:Guest Room Vent is 68.22°F]
4726a854-b87b-499b-a8e1-277a51f19442  8:53:05 PM: debug description: temperature: 20.12
20b15ba7-9456-4b1f-b52e-20910fadc0d2  8:53:00 PM: error java.lang.NumberFormatException @ line 68
20b15ba7-9456-4b1f-b52e-20910fadc0d2  8:53:00 PM: debug Updated with settings: [tempSensors:Nest, isACcapable:true, tStat:Nest]
20b15ba7-9456-4b1f-b52e-20910fadc0d2  8:52:59 PM: debug Installed with settings: [tempSensors:Nest, isACcapable:true, tStat:Nest]
e0dfb492-2d60-446e-bfdd-eb1104fc6d99  8:52:50 PM: debug Keenect DOES NOT RESPOND TO CHILD UNINSTALL HANDLER

**Comment by MikeMaxwell** [comment]
You need to set a cooling setpoint in the nest.

**Comment by caesra** [comment]
This resolved this particular error, but I still have several additional issues.  Would you like for me to present the additional issues here?

**Comment by MikeMaxwell** [comment]
You can do it here, or over in the smartthings thread, I prefer the community site, but whatever works for you.

**Comment by caesra** [comment]
I am going to do it here simply because there is so much cross talk over there, I find it difficult to follow a single conversation.  

I cannot add a zone through the smartthings app.  I have both apps published via GitHub integration, when I go to the kennectZone through the marketplace, I can access the setup screen, enter the information in (i am selecting a vent, then the temp sensor on the vent (i tried a diff temp sensor but same result), and fully closed.  Evertying else at default.  When I hit done I receive an error that says 'an unexpected error occurred'

Live logging reports 

a171de74-f0e5-4da9-b20b-918b9ab41125  6:36:47 PM: debug Parse returned [name:temperature, value:68.99, descriptionText:Basement Bathroom Vent is 68.99°F]
a171de74-f0e5-4da9-b20b-918b9ab41125  6:36:47 PM: debug description: temperature: 20.55
a171de74-f0e5-4da9-b20b-918b9ab41125  6:36:47 PM: debug Parse returned [name:pressure, descriptionText:Basement Bathroom Vent pressure is 98421.7Pa, value:98421.7]
a171de74-f0e5-4da9-b20b-918b9ab41125  6:36:47 PM: debug makePressureResut
a171de74-f0e5-4da9-b20b-918b9ab41125  6:36:47 PM: debug Desc Map: [raw:36920104030C20002299040F, dni:3692, endpoint:01, cluster:0403, size:0C, attrId:0020, encoding:22, value:0f0499]
a171de74-f0e5-4da9-b20b-918b9ab41125  6:36:47 PM: debug parseReportAttributeMessage
a171de74-f0e5-4da9-b20b-918b9ab41125  6:36:47 PM: debug description: read attr - raw: 36920104030C20002299040F, dni: 3692, endpoint: 01, cluster: 0403, size: 0C, attrId: 0020, encoding: 22, value: 0f0499
4322b156-5e78-4cb3-9205-ab67d7b0364d  6:36:45 PM: error java.lang.NullPointerException: Cannot invoke method currentValue() on null object @ line 404

If I go to My Locations > list smartapps I can see what I just generated, and it actually appears to be working but I am not 100% sure.

**Comment by caesra** [comment]
Additional issue, when setting up the main Keen settings, the UI, now that I have turned the AC setting back on, it says success, but If I go back in to the keen settings everything is empty.

It does show in my locations with the settings applied.

**Comment by caesra** [comment]
Additional Issue, if I attempt to use the simulator to control the app, I am able to get the main part to work, but the child app keenZone just sits and spins.  I did not know if you were attempting to ensure that the app functioned correctly via the simulator, but I wanted to call out that it does not appear to work correctly there.  I am happy to provide information, if you would like.

**Comment by MikeMaxwell** [comment]
Ok, pm me on the forums, at least I can get some screen caps that way.

**Comment by MikeMaxwell** [comment]
Btw, you have to set a cooling set point and a heating set point via st, at least once.  These nope errors are a result of these values being null in st.

**Comment by MikeMaxwell** [comment]
The Sim sucks, I haven't used it in two years.

**Comment by caesra** [comment]
I am not sure where you would do the set points other than in the zones, and those fields show as optional.  I have set them on some of my attempts, but they didn't appear to change anything.

**Comment by caesra** [comment]
Re: set points.  When attempting to add in zones

Setting fixed setpoint:

876dc1dd-4a92-4db4-8989-783b6f77110a  6:54:52 PM: error java.lang.NullPointerException: Cannot invoke method currentValue() on null object @ line 404
876dc1dd-4a92-4db4-8989-783b6f77110a  6:54:52 PM: debug Updated with settings: [minVo:0, staticCSP:68, maxVo:100, tempSensors:Guest Room Vent, coolOffset:0, heatOffset:0, staticHSP:68, zoneControlType:fixed, vents:[Guest Room Vent]]
a171de74-f0e5-4da9-b20b-918b9ab41125  6:54:51 PM: debug Parse returned [name:pressure, descriptionText:Basement Bathroom Vent pressure is 98451.6Pa, value:98451.6]
a171de74-f0e5-4da9-b20b-918b9ab41125  6:54:51 PM: debug makePressureResut
a171de74-f0e5-4da9-b20b-918b9ab41125  6:54:51 PM: debug Desc Map: [raw:36920104030C200022C4050F, dni:3692, endpoint:01, cluster:0403, size:0C, attrId:0020, encoding:22, value:0f05c4]
a171de74-f0e5-4da9-b20b-918b9ab41125  6:54:51 PM: debug parseReportAttributeMessage
a171de74-f0e5-4da9-b20b-918b9ab41125  6:54:51 PM: debug description: read attr - raw: 36920104030C200022C4050F, dni: 3692, endpoint: 01, cluster: 0403, size: 0C, attrId: 0020, encoding: 22, value: 0f05c4
a171de74-f0e5-4da9-b20b-918b9ab41125  6:54:51 PM: debug Parse returned [name:temperature, value:68.92, descriptionText:Basement Bathroom Vent is 68.92°F]
a171de74-f0e5-4da9-b20b-918b9ab41125  6:54:51 PM: debug description: temperature: 20.51


Setting offset setpoint:

Clear
876dc1dd-4a92-4db4-8989-783b6f77110a  6:56:18 PM: error java.lang.NullPointerException: Cannot invoke method currentValue() on null object @ line 404
876dc1dd-4a92-4db4-8989-783b6f77110a  6:56:18 PM: debug Updated with settings: [minVo:0, staticCSP:70, maxVo:100, tempSensors:Guest Room Vent, coolOffset:-1, heatOffset:-1, staticHSP:70, zoneControlType:offset, vents:[Guest Room Vent]]
