### ISSUE TITLE
Error Saving Page

### ISSUE THREAD

**Issue by benschwartz42** [MikeMaxwell/vmgr#3]
I get an error when I try to setup zones and get the same error when trying to install the app. Here is log from IDE.

ef5bb696-9f32-4dea-b2cd-1ec62f9fb0ad  5:11:24 PM: error java.lang.NullPointerException: Cannot invoke method toFloat() on null object
ef5bb696-9f32-4dea-b2cd-1ec62f9fb0ad  5:11:24 PM: debug Updated with settings: [heatOffset:0, maxVo:100, staticCSP:70, vents:[Keen Home Smart Vent front, Keen Home Smart Vent side], staticHSP:70, coolOffset:0, tempSensors:Nest - Living Room, minVo:15, zoneControlType:offset]
ef5bb696-9f32-4dea-b2cd-1ec62f9fb0ad  5:11:23 PM: debug Installed with settings: [heatOffset:0, maxVo:100, staticCSP:70, vents:[Keen Home Smart Vent front, Keen Home Smart Vent side], staticHSP:70, coolOffset:0, tempSensors:Nest - Living Room, minVo:15, zoneControlType:offset]

**Comment by benschwartz42** [comment]
Error and log when I install app:

eb33b952-16ea-46bd-aa31-341b868b71e5  5:14:10 PM: error java.lang.NullPointerException: Cannot invoke method toFloat() on null object
eb33b952-16ea-46bd-aa31-341b868b71e5  5:14:10 PM: debug Updated with settings: [isACcapable:true, tStat:Nest - Living Room, tempSensors:Nest - Living Room]
eb33b952-16ea-46bd-aa31-341b868b71e5  5:14:10 PM: debug Installed with settings: [isACcapable:true, tStat:Nest - Living Room, tempSensors:Nest - Living Room]

**Comment by MikeMaxwell** [comment]
Appears the nest isn't updating the temperature to keenect.  Try selecting  a different temp sensor for the thermostat.
